// user
export const GET_USER_NAME = 'GET_USER_NAME';
export const SET_USER_NAME = 'SET_USER_NAME';

export const GET_FRAME_NUMBER = 'GET_FRAME_NUMBER';
export const SET_FRAME_NUMBER = 'SET_FRAME_NUMBER';

export const GET_PROFILE_SETTINGS = 'GET_PROFILE_SETTINGS';
export const SET_PROFILE_SETTINGS = 'SET_PROFILE_SETTINGS';

export const GET_BIKES_DATA = 'GET_BIKES_DATA';
export const SET_BIKES_DATA = 'SET_BIKES_DATA';

export const SET_USER_BIKE = 'SET_USER_BIKE';
