// user
export const GET_USER_NAME = 'GET_USER_NAME';
export const SET_USER_NAME = 'SET_USER_NAME';
export const LOADING_USER_STATUS = 'LOADING_USER_STATUS';

export const GET_FRAME_NUMBER = 'GET_FRAME_NUMBER';
export const SET_FRAME_NUMBER = 'SET_FRAME_NUMBER';

/* Profile */
export const GET_PROFILE_SETTINGS = 'GET_PROFILE_SETTINGS';
export const SET_PROFILE_SETTINGS = 'SET_PROFILE_SETTINGS';
export const SET_PROFILE_SETTINGS_ERROR = 'SET_PROFILE_SETTINGS_ERROR';
export const SET_ONBOARDING_FINISHED = 'SET_ONBOARDING_FINISHED';

/* Bikes */
export const GET_BIKES_DATA = 'GET_BIKES_DATA';
export const SET_BIKE_DATA = 'SET_BIKE_DATA';
export const SET_BIKES_DATA = 'SET_BIKES_DATA';
export const REMOVE_BIKE_BY_NUMBER = 'REMOVE_BIKE_BY_NUMBER';
export const LOADING_BIKE_DATA_STATUS = 'LOADING_BIKE_DATA_STATUS';
export const SET_BIKES_ERROR = 'SET_BIKES_ERROR';
export const FETCH_GENERIC_BIKE_DATA = 'FETCH_GENERIC_BIKE_DATA';
export const SET_GENERIC_BIKE_DATA = 'SET_GENERIC_BIKE_DATA';

/* Places */
export const SET_PLACES_DATA = 'SET_PLACES_DATA';
export const LOADING_PLACES_DATA = 'LOADING_PLACES_DATA';
export const SET_PLACES_ERROR = 'SET_PLACES_ERROR';

/* App */
export const SET_APP_NETWORK_STATUS = 'SET_APP_NETWORK_STATUS';
export const SET_APP_CONFIG = 'SET_APP_CONFIG';
export const SET_APP_TERMS = 'SET_APP_TERMS';
export const SET_APP_CURRENT_TERMS = 'SET_APP_CURRENT_TERMS';
export const SET_APP_SHOWED_TERMS_VERSION = 'SET_APP_SHOWED_TERMS_VERSION';
export const SET_APP_REGULATION = 'SET_APP_REGULATION';
export const SET_APP_POLICY = 'SET_APP_POLICY';
export const SET_APP_FAQ = 'SET_APP_FAQ';
export const SET_SYNC_APP_DATA_STATUS = 'SET_SYNC_APP_DATA_STATUS';
export const SET_SYNC_APP_SYNC_ERROR = 'SET_SYNC_APP_SYNC_ERROR';
export const CLEAR_APP_ERROR = 'CLEAR_APP_ERROR';

export const LOGOUT = 'LOGOUT';

/* Maps */
export const SET_MAPS_DATA = 'SET_MAPS_DATA';
export const SET_PRIVATE_MAPS_DATA = 'SET_PRIVATE_MAPS_DATA';
export const SET_PRIVATE_MAP_METADATA = 'SET_PRIVATE_MAP_METADATA';
export const SET_MAP_DATA = 'SET_MAP_DATA';
export const SET_PRIVATE_MAPID_TO_ADD = 'SET_PRIVATE_MAPID_TO_ADD';
export const CLEAR_PRIVATE_MAPID_TO_ADD = 'CLEAR_PRIVATE_MAPID_TO_ADD';
export const SET_MAPS_ERROR = 'SET_MAPS_ERROR';
export const SET_MAPS_LOADING_STATE = 'SET_MAPS_LOADING_STATE';
export const SET_PLANNED_MAPS_DATA = 'SET_PLANNED_MAPS_DATA';
export const ADD_MAP_TO_FAVOURITES = 'ADD_MAP_TO_FAVOURITES';
export const REMOVE_MAP_FROM_FAVOURITES = 'REMOVE_MAP_FROM_FAVOURITES';
export const REMOVE_MAP_FROM_PRIVATES = 'REMOVE_MAP_FROM_PRIVATES';
export const CLEAR_MAPS_ERROR = 'CLEAR_MAPS_ERROR';

/* Routes */
export const SET_CURRENT_ROUTE = 'SET_CURRENT_ROUTE';
export const CLEAR_CURRENT_ROUTE = 'CLEAR_CURRENT_ROUTE';
export const SET_REMOTE_ROUTE_ID = 'SET_REMOTE_ROUTE_ID';
export const SET_CURRENT_ROUTE_DATA = 'SET_CURRENT_ROUTE_DATA';
export const SET_CURRENT_ROUTE_PAUSE_TIME = 'SET_CURRENT_ROUTE_PAUSE_TIME';
export const SET_AVERAGE_ROUTE_SPEED = 'SET_AVERAGE_ROUTE_SPEED';
export const SET_ROUTE_TO_SYNC = 'SET_ROUTE_TO_SYNC';
export const SET_ROUTES_TO_SYNC = 'SET_ROUTES_TO_SYNC';
export const CLEAR_CURRENT_ROUTE_DATA = 'CLEAR_CURRENT_ROUTE_DATA';
export const CLEAR_ROUTES_TO_SYNC = 'CLEAR_ROUTES_TO_SYNC';
export const CLEAR_AVERAGE_ROUTE_SPEED = 'CLEAR_AVERAGE_ROUTE_SPEED';
export const SET_ROUTES_DATA = 'SET_ROUTES_DATA';
export const SET_ROUTES_ERROR = 'SET_ROUTES_ERROR';
export const SET_ROUTES_LOADING_STATE = 'SET_ROUTES_LOADING_STATE';
export const CLEAR_ROUTES_ERROR = 'CLEAR_ROUTES_ERROR';

/* Auth */
export const SET_AUTH_STATE = 'SET_AUTH_STATE';
export const SET_NO_AUTH_STATE = 'SET_NO_AUTH_STATE';
export const SET_AUTH_DATA = 'SET_AUTH_DATA';
export const SET_AUTH_SYNC_STATE = 'SET_AUTH_SYNC_STATE';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';
export const SET_AUTH_SESSION_DATA = 'SET_AUTH_SESSION_DATA';
export const CLEAR_AUTH_SESSION_DATA = 'CLEAR_AUTH_SESSION_DATA';
