// user
export const GET_USER_NAME = 'GET_USER_NAME';
export const SET_USER_NAME = 'SET_USER_NAME';
export const LOADING_USER_STATUS = 'LOADING_USER_STATUS';

export const GET_FRAME_NUMBER = 'GET_FRAME_NUMBER';
export const SET_FRAME_NUMBER = 'SET_FRAME_NUMBER';

export const GET_PROFILE_SETTINGS = 'GET_PROFILE_SETTINGS';
export const SET_PROFILE_SETTINGS = 'SET_PROFILE_SETTINGS';
export const SET_PROFILE_SETTINGS_ERROR = 'SET_PROFILE_SETTINGS_ERROR';
export const SET_ONBOARDING_FINISHED = 'SET_ONBOARDING_FINISHED';

export const GET_BIKES_DATA = 'GET_BIKES_DATA';
export const SET_BIKE_DATA = 'SET_BIKE_DATA';
export const SET_BIKES_DATA = 'SET_BIKES_DATA';
export const REMOVE_BIKE_BY_NUMBER = 'REMOVE_BIKE_BY_NUMBER';
export const LOADING_BIKE_DATA_STATUS = 'LOADING_BIKE_DATA_STATUS';
export const SET_BIKES_ERROR = 'SET_BIKES_ERROR';
export const FETCH_GENERIC_BIKE_DATA = 'FETCH_GENERIC_BIKE_DATA';
export const SET_GENERIC_BIKE_DATA = 'SET_GENERIC_BIKE_DATA';

export const SET_PLACES_DATA = 'SET_PLACES_DATA';
export const LOADING_PLACES_DATA = 'LOADING_PLACES_DATA';
export const SET_PLACES_ERROR = 'SET_PLACES_ERROR';

export const SET_APP_NETWORK_STATUS = 'SET_APP_NETWORK_STATUS';
