require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

project 'myKROSS',
        'Dev.Debug' => :debug,
        'Dev.Release' => :release, 
        'Test.Debug' => :debug,
        'Test.Release' => :release, 
        'Feat.Debug' => :debug,
        'Feat.Release' => :release, 
        'Prod.Debug' => :debug,
        'Prod.Release' => :release

target 'myKROSS' do
  use_expo_modules!
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Motion', :path => "#{permissions_path}/Motion"

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'myKROSSTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({'Flipper' => '0.109.0'})

  ENVFILES = {
    'Dev.Debug' => '${PODS_ROOT}/../../.env.development',
    'Dev.Release' => '${PODS_ROOT}/../../.env.development', 
    'Test.Debug' => '${PODS_ROOT}/../.env.test',
    'Test.Release' => '${PODS_ROOT}/../.env.test', 
    'Feat.Debug' => '${PODS_ROOT}/../.env.feature',
    'Feat.Release' => '${PODS_ROOT}/../.env.feature', 
    'Prod.Debug' => '${PODS_ROOT}/../../.env.production',
    'Prod.Release' => '${PODS_ROOT}/../../.env.production'
  }

  post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
          if target.name == 'react-native-config'
            config.build_settings['ENVFILE'] = ENVFILES[config.name]
          end
        end
      end
    flipper_post_install(installer)
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
